// This file was auto-generated by ML.NET Model Builder. 

#region

using Microsoft.ML.Data;

#endregion

namespace CyberBackML.Model
{
    public class ModelInput
    {
        [ColumnName("Pulse"), LoadColumn(0)] public float Pulse { get; set; }


        [ColumnName("Temperature"), LoadColumn(1)]
        public float Temperature { get; set; }


        [ColumnName("Time"), LoadColumn(2)] public string Time { get; set; }


        [ColumnName("Place"), LoadColumn(3)] public string Place { get; set; }


        [ColumnName("Outcome"), LoadColumn(4)] public string Outcome { get; set; }
    }
}