//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CyberDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Player
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Player()
        {
            this.Health = new HashSet<Health>();
        }
    
        public int player_id { get; set; }
        public string player_lastname { get; set; }
        public string player_firstname { get; set; }
        public string player_birthdate { get; set; }
        public string player_country { get; set; }
        public string player_login { get; set; }
        public string player_password { get; set; }
        public Nullable<int> team_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Health> Health { get; set; }
        public virtual Team Team { get; set; }
    }
}
