//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CyberDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Team_Tournament
    {
        public int team_tournament_id { get; set; }
        public Nullable<int> team_id { get; set; }
        public Nullable<int> tournament_id { get; set; }
    
        public virtual Team Team { get; set; }
        public virtual Tournament Tournament { get; set; }
    }
}
