//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CyberDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tournament
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tournament()
        {
            this.Team_Tournament = new HashSet<Team_Tournament>();
        }
    
        public int tournament_id { get; set; }
        public string tournament_name { get; set; }
        public string tournament_type { get; set; }
        public string tournament_startdate { get; set; }
        public string tournament_enddate { get; set; }
        public string tournament_location { get; set; }
        public Nullable<int> game_id { get; set; }
        public Nullable<int> organizer_id { get; set; }
    
        public virtual Game Game { get; set; }
        public virtual Organizer Organizer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Team_Tournament> Team_Tournament { get; set; }
    }
}
