// This file was auto-generated by ML.NET Model Builder. 

#region

using System;
using CyberBackML.Model;

#endregion

namespace CyberBackML.ConsoleApp
{
    class Program
    {
        static void Main(string[] args)
        {

            var sampleData = new ModelInput
            {
                Pulse = 60F,
                Temperature = 36.7F,
                Time = @"16:00",
                Place = @"Home",
            };

            var predictionResult = ConsumeModel.Predict(sampleData);

            Console.WriteLine($"Pulse: {sampleData.Pulse}");
            Console.WriteLine($"Temperature: {sampleData.Temperature}");
            Console.WriteLine($"Time: {sampleData.Time}");
            Console.WriteLine($"Place: {sampleData.Place}");
            Console.WriteLine($"\n\nPredicted Outcome value {predictionResult.Prediction}");
            Console.ReadKey();
        }
    }
}